### PR TITLE
search items

### PR DESCRIPTION
**Pull request by cryptomadvad**

### CODE REVIEW

**Comment by ArtemGr** [comment]
Thanks!
Per https://github.com/mercatos/Ebay/issues/2#issuecomment-1215688451, would like you to include an example of [epid](https://developer.ebay.com/api-docs/buy/browse/resources/item_summary/methods/search) search.

**Comment by cryptomadvad** [comment]
> Thanks! Per [#2 (comment)](https://github.com/mercatos/Ebay/issues/2#issuecomment-1215688451), would like you to include an example of [epid](https://developer.ebay.com/api-docs/buy/browse/resources/item_summary/methods/search) search.

updated code pushed

**Comment by cryptomadvad** [comment]
waiting for the update

**Comment by ArtemGr** [comment]
Yeah, had a bit of a grace period for comments, I'll go ahead and merge now. Thanks for your help with the API!

**Comment by cryptomadvad** [comment]
@ArtemGr how about the pay for this task?

**Pull request merged**
