### PR TITLE
Get product detail by item id

### LINKED ISSUE #2: Script for get detailed Product-Information on Ebay via API by item-id [$100 awarded]
Preferred programming language: **Python**, Rust... php
**API keys will be provided...**

It is required to write a script to get detailed information about products on ebay through the API by item-id (
  https://developer.ebay.com/api-docs/buy/browse/resources/item/methods/getItem The received information should be output in JSON format.

**Mandatory information you need to get about the product:**

- product.title
- product.description
- product.brand
- product.gtins
- product.image
- product.mpns
- itemLocation
- price + Currency
- buyingOption
- condition
- maybe a few more...

<bountysource-plugin>

---
The **[$100 bounty](https://app.bountysource.com/issues/110649807-script-for-get-detailed-product-information-on-ebay-via-api-by-item-id?utm_campaign=plugin&utm_content=tracker%2F224120225&utm_medium=issues&utm_source=github)** on this issue has been claimed at [Bountysource](https://app.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F224120225&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ThakurKarthik**
- Added the code for fetching the access token and using that getting the product details. I have not setup any full fledged [python project](https://docs.python-guide.org/writing/structure/) as it was not clear to me if we wanted to write just scripts and not a full python project.

- Right now I am hitting the sandbox urls. We can change this to use the production based on some environment variable.

During my research for getting the oauth I wanted to use the [ebay written sdk](https://github.com/eBay/ebay-oauth-python-client)  but there was no pip package available and it is not compatible to python3 (see the open issues) and I also believe that project is not maintained actively. So I wrote a small function to fetch the access token as per the dev docs.

@fropl  please review this. I was not able to see the fields _brand_, _gtins_, _mpns_ on this end point. May be they can be fetched through some dedicated endpoint, please advise.

Should close #2 after review and merged.

### CODE REVIEW

**Comment by fropl** [comment]
> @fropl please review this. I was not able to see the fields brand, gtins, mpns on this end point. May be they can be fetched through some dedicated endpoint, please advise.

Good evening and thanks for the information, I will comment a bit later.

Please, to get the brand, mpn... try this product https://www.ebay.com/itm/175383505525

**Comment by ArtemGr** [comment]
> if we wanted to write just scripts and not a full python project

Just scripts!

> Right now I am hitting the sandbox urls. We can change this to use the production based on some environment variable.

Yep, let's change to production auth and URLs when the corresponding environment variables are present.

**Comment by ThakurKarthik** [comment]
I have now created a generic config file to read the values like client_id and client_secret from environment variables. To test this change, please set the different environment variable like this

```
export client_id=<client-id>
export client_secret=<client-secret>
export is_dev_environment=<1 | 0> //set this value to 1 or 0 to hit prod or sandbox urls
```
I believe this pr is now ready for review and can be integrated with the changes from the PR of the first issue, they just need to pass itemid to my method.

**Comment by fropl** [comment]
Hi @ThakurKarthik  and thanks for your work! 

I completely forgot to specify the receipt of these fields:

"categoryId" : "string",
"categoryIdPath" : "string",
"categoryPath" : "string",

If it's not difficult, please add them to the code too.

Thanks in advance
Maxim

**Comment by ThakurKarthik** [comment]
@fropl Looking at the main branch code, I see we are not extracting specific fields any more, so all the available data can be consumed by the caller of the fetch_item cc @ArtemGr

**Comment by ArtemGr** [comment]
Yes, we can see the `categoryPath` in the [logs](https://github.com/mercatos/Ebay/runs/7887916051).
I wonder if you've seen a mention of how to get the `categoryIdPath`.

**Comment by ThakurKarthik** [comment]
@ArtemGr I have looked hard for this and I think I found something, you need to make a request to this

`https://open.api.ebay.com/Shopping?responseencoding=JSON&callname=GetCategoryInfo&version=967&siteid=0&CategoryID={categoryId}`

I tried with categoryId = 1244

with this header

```
headers = {
    'X-EBAY-API-IAF-TOKEN': f"Bearer {credentials['access_token']}"
  }
```
You can use the category id from the getItem response.

This is the output
image

I am not sure if it is that efficient, this is the doc I followed 
https://forums.developer.ebay.com/questions/39222/getting-category-name-from-category-id.html
https://developer.ebay.com/Devzone/shopping/docs/CallRef/GetCategoryInfo.html#Samples
https://developer.ebay.com/Devzone/shopping/docs/Concepts/ShoppingAPI_FormatOverview.html

**Pull request merged**
